pred = input("Введите предложение на английском: ")
print(f"Длина предложения: {len(pred)}")
print(f"В нижнем регистре: {pred.lower()}")
glas = sum(1 for kolv in pred.lower() if kolv in 'aeiou')
print(f"Количество гласных: {glas}")
change = pred.replace('ugly', 'beauty')
print(f"После замены 'ugly' на 'beauty': {change}")
start = pred.startswith('The')
ends = pred.endswith('end')
print(f"Начинается с 'The': {start}")
print(f"Заканчивается на 'end': {ends}")